cp ./caltech101/train_ssf.sh ./caltech101/train_linear_probe.sh
cp ./cifar_100/train_ssf.sh ./cifar_100/train_linear_probe.sh
cp ./clevr_count/train_ssf.sh ./clevr_count/train_linear_probe.sh
cp ./clevr_dist/train_ssf.sh ./clevr_dist/train_linear_probe.sh
cp ./diabetic_retinopathy/train_ssf.sh ./diabetic_retinopathy/train_linear_probe.sh
cp ./dmlab/train_ssf.sh ./dmlab/train_linear_probe.sh
cp ./dsprites_loc/train_ssf.sh ./dsprites_loc/train_linear_probe.sh
cp ./dsprites_ori/train_ssf.sh ./dsprites_ori/train_linear_probe.sh
cp ./dtd/train_ssf.sh ./dtd/train_linear_probe.sh
cp ./eurosat/train_ssf.sh ./eurosat/train_linear_probe.sh
cp ./flowers102/train_ssf.sh ./flowers102/train_linear_probe.sh
cp ./kitti/train_ssf.sh ./kitti/train_linear_probe.sh
cp ./patch_camelyon/train_ssf.sh ./patch_camelyon/train_linear_probe.sh
cp ./pets/train_ssf.sh ./pets/train_linear_probe.sh
cp ./resisc45/train_ssf.sh ./resisc45/train_linear_probe.sh
cp ./smallnorb_azi/train_ssf.sh ./smallnorb_azi/train_linear_probe.sh
cp ./smallnorb_ele/train_ssf.sh ./smallnorb_ele/train_linear_probe.sh
cp ./sun397/train_ssf.sh ./sun397/train_linear_probe.sh
cp ./svhn/train_ssf.sh ./svhn/train_linear_probe.sh