bash train_scripts/vit/vtab/caltech101/train_ssf.sh $1
bash train_scripts/vit/vtab/cifar_100/train_ssf.sh $1
bash train_scripts/vit/vtab/clevr_count/train_ssf.sh $1
bash train_scripts/vit/vtab/clevr_dist/train_ssf.sh $1
bash train_scripts/vit/vtab/diabetic_retinopathy/train_ssf.sh $1
bash train_scripts/vit/vtab/dmlab/train_ssf.sh $1
bash train_scripts/vit/vtab/dsprites_loc/train_ssf.sh $1
bash train_scripts/vit/vtab/dsprites_ori/train_ssf.sh $1
bash train_scripts/vit/vtab/dtd/train_ssf.sh $1
bash train_scripts/vit/vtab/eurosat/train_ssf.sh $1
bash train_scripts/vit/vtab/flowers102/train_ssf.sh $1
bash train_scripts/vit/vtab/kitti/train_ssf.sh $1
bash train_scripts/vit/vtab/patch_camelyon/train_ssf.sh $1
bash train_scripts/vit/vtab/pets/train_ssf.sh $1
bash train_scripts/vit/vtab/resisc45/train_ssf.sh $1
bash train_scripts/vit/vtab/smallnorb_azi/train_ssf.sh $1
bash train_scripts/vit/vtab/smallnorb_ele/train_ssf.sh $1
bash train_scripts/vit/vtab/sun397/train_ssf.sh $1
bash train_scripts/vit/vtab/svhn/train_ssf.sh $1
