sleep $3
bash train_scripts/vit/vtab/caltech101/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/cifar_100/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/clevr_count/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/clevr_dist/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/diabetic_retinopathy/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/dmlab/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/dsprites_loc/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/dsprites_ori/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/dtd/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/eurosat/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/flowers102/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/kitti/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/patch_camelyon/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/pets/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/resisc45/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/smallnorb_azi/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/smallnorb_ele/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/sun397/train_linear_probe.sh $1 $2
bash train_scripts/vit/vtab/svhn/train_linear_probe.sh $1 $2