source DATA_PATH.sh
bash pruning/vtab/caltech101/train_ssf.sh $1 $2
bash pruning/vtab/cifar_100/train_ssf.sh $1 $2
bash pruning/vtab/clevr_count/train_ssf.sh $1 $2
bash pruning/vtab/clevr_dist/train_ssf.sh $1 $2
bash pruning/vtab/diabetic_retinopathy/train_ssf.sh $1 $2
bash pruning/vtab/dmlab/train_ssf.sh $1 $2
bash pruning/vtab/dsprites_loc/train_ssf.sh $1 $2
bash pruning/vtab/dsprites_ori/train_ssf.sh $1 $2
bash pruning/vtab/dtd/train_ssf.sh $1 $2
bash pruning/vtab/eurosat/train_ssf.sh $1 $2
bash pruning/vtab/flowers102/train_ssf.sh $1 $2
bash pruning/vtab/kitti/train_ssf.sh $1 $2
bash pruning/vtab/patch_camelyon/train_ssf.sh $1 $2
bash pruning/vtab/pets/train_ssf.sh $1 $2
bash pruning/vtab/resisc45/train_ssf.sh $1 $2
bash pruning/vtab/smallnorb_azi/train_ssf.sh $1 $2
bash pruning/vtab/smallnorb_ele/train_ssf.sh $1 $2
bash pruning/vtab/sun397/train_ssf.sh $1 $2
bash pruning/vtab/svhn/train_ssf.sh $1 $2